-- Switch to PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- Create application user
CREATE USER welldata IDENTIFIED BY Oracle123
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE, CREATE VIEW TO welldata;
GRANT CREATE SESSION TO welldata;

-- Base tables (never queried directly by the agent)
CREATE TABLE welldata.WELL (
  UWI           VARCHAR2(20)   PRIMARY KEY,
  WELL_NAME     VARCHAR2(100)  NOT NULL,
  OPERATOR      VARCHAR2(100),
  COUNTRY       VARCHAR2(50)   DEFAULT 'India',
  BASIN         VARCHAR2(50),
  FIELD_NAME    VARCHAR2(100),
  SPUD_DATE     DATE,
  COMPLETION_DATE DATE,
  WELL_TYPE     VARCHAR2(30),   -- EXPLORATION, DEVELOPMENT, APPRAISAL
  WELL_STATUS   VARCHAR2(30),   -- ACTIVE, ABANDONED, SUSPENDED
  SURFACE_LAT   NUMBER(9,6),
  SURFACE_LON   NUMBER(9,6),
  TOTAL_DEPTH_M NUMBER(8,2),
  KB_ELEVATION_M NUMBER(8,2)
);

CREATE TABLE welldata.BOREHOLE (
  UBHI          VARCHAR2(20)   PRIMARY KEY,
  UWI           VARCHAR2(20)   NOT NULL REFERENCES welldata.WELL(UWI),
  BOREHOLE_NAME VARCHAR2(100),
  BOREHOLE_TYPE VARCHAR2(30),  -- VERTICAL, DIRECTIONAL, HORIZONTAL
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2)
);

CREATE TABLE welldata.PETROPHYSICS (
  UBHI          VARCHAR2(20)   REFERENCES welldata.BOREHOLE(UBHI),
  SAMPLE_DEPTH_M NUMBER(8,2),
  POROSITY      NUMBER(6,4),   -- fraction 0-1
  PERMEABILITY  NUMBER(10,4),  -- millidarcy
  WATER_SAT     NUMBER(6,4),   -- fraction 0-1
  FORMATION     VARCHAR2(50),
  CONSTRAINT pk_petro PRIMARY KEY (UBHI, SAMPLE_DEPTH_M)
);

CREATE TABLE welldata.PRODUCTION (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  PROD_DATE     DATE,
  OIL_BBL       NUMBER(12,2),
  GAS_MCF       NUMBER(12,2),
  WATER_BBL     NUMBER(12,2),
  HOURS_ON      NUMBER(5,2),
  CONSTRAINT pk_prod PRIMARY KEY (UWI, PROD_DATE)
);

CREATE TABLE welldata.FORMATION_TOPS (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  FORMATION     VARCHAR2(50),
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2),
  LITHOLOGY     VARCHAR2(30),  -- SANDSTONE, LIMESTONE, SHALE, DOLOMITE
  CONSTRAINT pk_tops PRIMARY KEY (UWI, FORMATION)
);

CREATE TABLE welldata.CORE_ANALYSIS (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  CORE_RUN      NUMBER(3),
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2),
  GRAIN_DENSITY NUMBER(6,4),
  BULK_DENSITY  NUMBER(6,4),
  RECOVERY_PCT  NUMBER(5,2),
  CONSTRAINT pk_core PRIMARY KEY (UWI, CORE_RUN)
);

CREATE TABLE welldata.NATURAL_GAS_COMPOSITION (
  UWI               VARCHAR2(20)  NOT NULL,
  SAMPLE_DATE       DATE          NOT NULL,
  METHANE_PCT       NUMBER(6,3),   -- CH4 percentage by volume
  ETHANE_PCT        NUMBER(6,3),   -- C2H6 percentage by volume
  PROPANE_PCT       NUMBER(6,3),   -- C3H8 percentage by volume
  BUTANE_PCT        NUMBER(6,3),   -- C4H10 percentage by volume
  PENTANE_PCT       NUMBER(6,3),   -- C5H12 percentage by volume
  CO2_PCT           NUMBER(6,3),   -- Carbon dioxide percentage
  H2S_PCT           NUMBER(6,3),   -- Hydrogen sulfide percentage
  N2_PCT            NUMBER(6,3),   -- Nitrogen percentage
  HEATING_VALUE_BTU NUMBER(8,2),   -- Gross heating value BTU/SCF
  SPECIFIC_GRAVITY  NUMBER(6,4),   -- Relative to air = 1.0
  SAMPLE_TYPE       VARCHAR2(30),  -- WELLHEAD, SEPARATOR, PIPELINE
  LAB_REFERENCE     VARCHAR2(30),
  CONSTRAINT pk_gas_comp PRIMARY KEY (UWI, SAMPLE_DATE),
  CONSTRAINT fk_gas_well FOREIGN KEY (UWI) REFERENCES welldata.WELL(UWI)
);
