-- Create application user
CREATE USER welldata IDENTIFIED BY Oracle123
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;
GRANT CONNECT, RESOURCE, CREATE VIEW TO welldata;

-- Base tables (never queried directly by the agent)
CREATE TABLE welldata.WELL (
  UWI           VARCHAR2(20)   PRIMARY KEY,
  WELL_NAME     VARCHAR2(100)  NOT NULL,
  OPERATOR      VARCHAR2(100),
  COUNTRY       VARCHAR2(50)   DEFAULT 'India',
  BASIN         VARCHAR2(50),
  FIELD_NAME    VARCHAR2(100),
  SPUD_DATE     DATE,
  COMPLETION_DATE DATE,
  WELL_TYPE     VARCHAR2(30),   -- EXPLORATION, DEVELOPMENT, APPRAISAL
  WELL_STATUS   VARCHAR2(30),   -- ACTIVE, ABANDONED, SUSPENDED
  SURFACE_LAT   NUMBER(9,6),
  SURFACE_LON   NUMBER(9,6),
  TOTAL_DEPTH_M NUMBER(8,2),
  KB_ELEVATION_M NUMBER(8,2)
);

CREATE TABLE welldata.BOREHOLE (
  UBHI          VARCHAR2(20)   PRIMARY KEY,
  UWI           VARCHAR2(20)   NOT NULL REFERENCES welldata.WELL(UWI),
  BOREHOLE_NAME VARCHAR2(100),
  BOREHOLE_TYPE VARCHAR2(30),  -- VERTICAL, DIRECTIONAL, HORIZONTAL
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2)
);

CREATE TABLE welldata.PETROPHYSICS (
  UBHI          VARCHAR2(20)   REFERENCES welldata.BOREHOLE(UBHI),
  SAMPLE_DEPTH_M NUMBER(8,2),
  POROSITY      NUMBER(6,4),   -- fraction 0-1
  PERMEABILITY  NUMBER(10,4),  -- millidarcy
  WATER_SAT     NUMBER(6,4),   -- fraction 0-1
  FORMATION     VARCHAR2(50),
  CONSTRAINT pk_petro PRIMARY KEY (UBHI, SAMPLE_DEPTH_M)
);

CREATE TABLE welldata.PRODUCTION (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  PROD_DATE     DATE,
  OIL_BBL       NUMBER(12,2),
  GAS_MCF       NUMBER(12,2),
  WATER_BBL     NUMBER(12,2),
  HOURS_ON      NUMBER(5,2),
  CONSTRAINT pk_prod PRIMARY KEY (UWI, PROD_DATE)
);

CREATE TABLE welldata.FORMATION_TOPS (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  FORMATION     VARCHAR2(50),
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2),
  LITHOLOGY     VARCHAR2(30),  -- SANDSTONE, LIMESTONE, SHALE, DOLOMITE
  CONSTRAINT pk_tops PRIMARY KEY (UWI, FORMATION)
);

CREATE TABLE welldata.CORE_ANALYSIS (
  UWI           VARCHAR2(20)   REFERENCES welldata.WELL(UWI),
  CORE_RUN      NUMBER(3),
  TOP_DEPTH_M   NUMBER(8,2),
  BASE_DEPTH_M  NUMBER(8,2),
  GRAIN_DENSITY NUMBER(6,4),
  BULK_DENSITY  NUMBER(6,4),
  RECOVERY_PCT  NUMBER(5,2),
  CONSTRAINT pk_core PRIMARY KEY (UWI, CORE_RUN)
);
