-- V_WELL_HEADER: master well information
CREATE OR REPLACE VIEW welldata.V_WELL_HEADER AS
SELECT
  w.UWI,
  w.UWI AS UBHI,
  w.WELL_NAME,
  w.OPERATOR,
  w.COUNTRY,
  w.BASIN,
  w.FIELD_NAME,
  w.SPUD_DATE,
  w.COMPLETION_DATE,
  w.WELL_TYPE,
  w.WELL_STATUS,
  w.SURFACE_LAT,
  w.SURFACE_LON,
  w.TOTAL_DEPTH_M,
  w.KB_ELEVATION_M,
  MONTHS_BETWEEN(NVL(w.COMPLETION_DATE, SYSDATE), w.SPUD_DATE) AS DRILL_DURATION_MONTHS
FROM welldata.WELL w;

-- V_PETROPHYSICS: reservoir quality per borehole and depth
CREATE OR REPLACE VIEW welldata.V_PETROPHYSICS AS
SELECT
  b.UBHI,
  b.UWI,
  b.BOREHOLE_TYPE,
  p.SAMPLE_DEPTH_M,
  p.POROSITY,
  p.PERMEABILITY,
  p.WATER_SAT,
  (1 - p.WATER_SAT) AS OIL_SAT,
  p.FORMATION,
  CASE
    WHEN p.POROSITY > 0.20 THEN 'EXCELLENT'
    WHEN p.POROSITY > 0.12 THEN 'GOOD'
    WHEN p.POROSITY > 0.05 THEN 'FAIR'
    ELSE 'POOR'
  END AS RESERVOIR_QUALITY
FROM welldata.BOREHOLE b
JOIN welldata.PETROPHYSICS p ON b.UBHI = p.UBHI;

-- V_PRODUCTION_MONTHLY: monthly production per well
CREATE OR REPLACE VIEW welldata.V_PRODUCTION_MONTHLY AS
SELECT
  p.UWI,
  w.WELL_NAME,
  w.OPERATOR,
  w.FIELD_NAME,
  p.PROD_DATE,
  EXTRACT(YEAR FROM p.PROD_DATE)  AS PROD_YEAR,
  EXTRACT(MONTH FROM p.PROD_DATE) AS PROD_MONTH,
  p.OIL_BBL,
  p.GAS_MCF,
  p.WATER_BBL,
  p.HOURS_ON,
  ROUND(p.OIL_BBL / NULLIF(p.HOURS_ON, 0), 2) AS OIL_RATE_BOPD,
  ROUND(p.GAS_MCF / NULLIF(p.HOURS_ON, 0), 2) AS GAS_RATE_MCFPD
FROM welldata.PRODUCTION p
JOIN welldata.WELL w ON p.UWI = w.UWI;

-- V_FORMATION_TOPS: stratigraphic column per well
CREATE OR REPLACE VIEW welldata.V_FORMATION_TOPS AS
SELECT
  f.UWI,
  w.WELL_NAME,
  w.BASIN,
  f.FORMATION,
  f.TOP_DEPTH_M,
  f.BASE_DEPTH_M,
  (f.BASE_DEPTH_M - f.TOP_DEPTH_M) AS THICKNESS_M,
  f.LITHOLOGY
FROM welldata.FORMATION_TOPS f
JOIN welldata.WELL w ON f.UWI = w.UWI;

-- V_WELL_SUMMARY: aggregated stats per well (designed for dashboards)
CREATE OR REPLACE VIEW welldata.V_WELL_SUMMARY AS
SELECT
  w.UWI,
  w.WELL_NAME,
  w.OPERATOR,
  w.FIELD_NAME,
  w.WELL_TYPE,
  w.WELL_STATUS,
  w.SPUD_DATE,
  w.TOTAL_DEPTH_M,
  SUM(p.OIL_BBL)       AS CUMULATIVE_OIL_BBL,
  SUM(p.GAS_MCF)       AS CUMULATIVE_GAS_MCF,
  SUM(p.WATER_BBL)     AS CUMULATIVE_WATER_BBL,
  COUNT(p.PROD_DATE)   AS PRODUCING_MONTHS,
  AVG(pe.POROSITY)     AS AVG_POROSITY,
  AVG(pe.PERMEABILITY) AS AVG_PERMEABILITY
FROM welldata.WELL w
LEFT JOIN welldata.PRODUCTION p   ON w.UWI = p.UWI
LEFT JOIN welldata.BOREHOLE b     ON w.UWI = b.UWI
LEFT JOIN welldata.PETROPHYSICS pe ON b.UBHI = pe.UBHI
GROUP BY
  w.UWI, w.WELL_NAME, w.OPERATOR, w.FIELD_NAME,
  w.WELL_TYPE, w.WELL_STATUS, w.SPUD_DATE, w.TOTAL_DEPTH_M;

-- V_CORE_ANALYSIS: lab measurements per well
CREATE OR REPLACE VIEW welldata.V_CORE_ANALYSIS AS
SELECT
  c.UWI,
  w.WELL_NAME,
  w.FIELD_NAME,
  c.CORE_RUN,
  c.TOP_DEPTH_M,
  c.BASE_DEPTH_M,
  c.GRAIN_DENSITY,
  c.BULK_DENSITY,
  c.RECOVERY_PCT,
  ROUND((1 - c.BULK_DENSITY / NULLIF(c.GRAIN_DENSITY, 0)), 4) AS COMPUTED_POROSITY
FROM welldata.CORE_ANALYSIS c
JOIN welldata.WELL w ON c.UWI = w.UWI;
